### ISSUE TITLE
Investigate issue with "run spectrum" (not working over full nozzle temp range)

### ISSUE THREAD

**Issue by spectroscopy** [RastonLab/Virtual-HeNDI-Spectrometer#3]
error returned for some nozzle temps (eg 19.5 K). It used to work just fine.
![image](https://user-images.githubusercontent.com/75122115/172398915-d1fb6bdb-021c-490a-80ef-3cf2667004a5.png)

**Comment by Brennaser** [comment]
I did some digging and it seems like this issue is specifically on Issac's website. The version that we are working from is running as expected.

I think Issac's site is having an issue with either interpolation, caching, or both since I only got errors, empty spectra, or very weird spectra on temperatures that are in between the data set we have.

**Comment by spectroscopy** [comment]
Glad to hear it! How do I access the version you are working from, or is it running locally?
